/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import React, { useEffect } from "react";
import { useLoader, useThree } from "react-three-fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { renderSensor } from "./utils";

export default function BasementModel(props) {
  const { camera } = useThree();

  const context = useLoader(
    GLTFLoader,
    "http://129.169.72.175/static/models/basement-context.glb"
  );

  useEffect(() => {
    camera.zoom = props.zoom * 0.6;
    camera.updateProjectionMatrix();
  }, [props.zoom]);

  return (
    <group {...props} dispose={null}>
      <scene name="Scene">
        {props.showContext ? (
          <group name="Z_UP">
            <mesh
              geometry={context.nodes["0aOA0Goyb51O9g4ENGh6mQ"].geometry}
              name="0aOA0Goyb51O9g4ENGh6mQ"
              position={[15, 2, 18]}
              rotation={[-Math.PI, 0, -Math.PI]}
            >
              <meshBasicMaterial
                attach="material"
                color={"grey"}
                transparent={true}
                opacity={0.4}
              />
            </mesh>
          </group>
        ) : null}
        <group
          name="Basement raft and wall sensors"
          position={[6.5, -1.5, -4.3]}
        >
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot01",
            [-8.42, 0.1, 1.8],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot02",
            [-8.42, 0.1, 2.8],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot03",
            [-8.42, 0.1, 3.8],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot04",
            [-8.42, 0.1, 4.8],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot05",
            [-8.42, 0.1, 5.8],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot06",
            [-8.42, 0.1, 6.8],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot07",
            [-8.42, 0.1, 7.8],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot08",
            [-8.42, 0.1, 8.8],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot09",
            [-8.42, 0.1, 9.8],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot10",
            [-8.42, 0.1, 10.8],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot11",
            [-8.42, 0.1, 11.8],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot12",
            [-8.42, 0.1, 12.8],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot13",
            [-8.42, 0.1, 13.8],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot14",
            [-8.42, 0.1, 14.8],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot15",
            [-8.42, 0.1, 15.8],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot16",
            [-8.42, 0.1, 16.8],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot17",
            [-8.42, 0.1, 17.8],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot18",
            [-8.42, 0.1, 18.8],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot19",
            [-8.42, 0.1, 19.8],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot20",
            [-8.42, 0.1, 20.8],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top01",
            [-8.42, 0.45, 1.81],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top02",
            [-8.42, 0.45, 2.81],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top03",
            [-8.42, 0.45, 3.81],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top04",
            [-8.42, 0.45, 4.81],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top05",
            [-8.42, 0.45, 5.81],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top06",
            [-8.42, 0.45, 6.81],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top07",
            [-8.42, 0.45, 7.81],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top08",
            [-8.42, 0.45, 8.81],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top09",
            [-8.42, 0.45, 9.81],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top10",
            [-8.42, 0.45, 10.81],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top11",
            [-8.42, 0.45, 11.81],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top12",
            [-8.42, 0.45, 12.81],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top13",
            [-8.42, 0.45, 13.81],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top14",
            [-8.42, 0.45, 14.81],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top15",
            [-8.42, 0.45, 15.81],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top16",
            [-8.42, 0.45, 16.81],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top17",
            [-8.42, 0.45, 17.81],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top18",
            [-8.42, 0.45, 18.81],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top19",
            [-8.42, 0.45, 19.81],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top20",
            [-8.42, 0.45, 20.79],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot01",
            [-0.81, 0.08, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot02",
            [-1.81, 0.08, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot03",
            [-2.81, 0.08, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot04",
            [-3.81, 0.08, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot05",
            [-4.81, 0.08, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot06",
            [-5.81, 0.08, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot07",
            [-6.81, 0.08, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot08",
            [-7.81, 0.08, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot09",
            [-8.81, 0.08, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot10",
            [-9.81, 0.08, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot11",
            [-10.81, 0.08, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot12",
            [-11.81, 0.08, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot13",
            [-12.81, 0.08, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot14",
            [-13.8, 0.08, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top01",
            [-0.79, 0.43, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top02",
            [-1.79, 0.43, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top03",
            [-2.79, 0.43, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top04",
            [-3.79, 0.43, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top05",
            [-4.79, 0.43, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top06",
            [-5.79, 0.43, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top07",
            [-6.79, 0.43, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top08",
            [-7.79, 0.43, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top09",
            [-8.79, 0.43, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top10",
            [-9.79, 0.43, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top11",
            [-10.79, 0.43, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top12",
            [-11.79, 0.43, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top13",
            [-12.79, 0.43, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top14",
            [-13.81, 0.43, 11.21],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Tmp_bot03",
            [-8.42, 0.1, 16.71],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Tmp_top01",
            [-8.42, 0.45, 6.29],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Tmp_top02",
            [-8.42, 0.45, 11.46],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Tmp_top03",
            [-8.42, 0.45, 16.7],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EE01_Str_wal01",
            [-8.42, 0.7, 21.89],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EE01_Str_wal02",
            [-8.42, 1.78, 21.89],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EE01_Str_wal03",
            [-8.42, 0.7, 21.73],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EE01_Str_wal04",
            [-8.42, 1.68, 21.73],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EE01_Tmp_wal05",
            [-8.42, 1.2, 21.89],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EE01_Tmp_wal06",
            [-8.42, 1.19, 21.73],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EE01_Str_thk01",
            [-8.42, 0.8, 21.59],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EE01_Str_thk02",
            [-8.42, 1.8, 21.59],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EE01_Str_thk03",
            [-8.42, 0.8, 21.01],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EE01_Str_thk04",
            [-8.42, 1.8, 21.01],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EE01_Tmp_thk05",
            [-8.42, 1.0, 21.59],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EE01_Tmp_thk06",
            [-8.42, 1.0, 21.01],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_WW01_Str_wal01",
            [-8.42, 0.7, 0.57],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_WW01_Str_wal02",
            [-8.42, 1.79, 0.57],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_WW01_Str_wal03",
            [-8.42, 0.7, 0.73],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_WW01_Str_wal04",
            [-8.42, 1.7, 0.73],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_WW01_Tmp_wal05",
            [-8.42, 1.2, 0.57],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_WW01_Tmp_wal06",
            [-8.42, 1.2, 0.73],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_WW01_Str_thk01",
            [-8.42, 0.8, 0.87],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_WW01_Str_thk02",
            [-8.42, 1.77, 0.87],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_WW01_Str_thk03",
            [-8.42, 0.8, 1.43],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_WW01_Str_thk04",
            [-8.42, 1.88, 1.43],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_WW01_Tmp_thk05",
            [-8.42, 1.0, 0.87],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_WW01_Tmp_thk06",
            [-8.42, 1.0, 1.43],
            [0.3, 0.6, 0.1]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NN01_Str_wal01",
            [-0.57, 0.69, 11.21],
            [0.1, 0.6, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NN01_Str_wal02",
            [-0.57, 1.69, 11.21],
            [0.1, 0.6, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NN01_Str_wal03",
            [-0.73, 0.7, 11.21],
            [0.1, 0.6, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NN01_Str_wal04",
            [-0.73, 1.69, 11.21],
            [0.1, 0.6, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NN01_Tmp_wal05",
            [-0.57, 1.2, 11.21],
            [0.1, 0.6, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NN01_Tmp_wal06",
            [-0.73, 1.2, 11.21],
            [0.1, 0.6, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_SS01_Str_wal01",
            [-14.05, 0.7, 11.21],
            [0.1, 0.6, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_SS01_Str_wal02",
            [-14.05, 1.7, 11.21],
            [0.1, 0.6, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_SS01_Str_wal03",
            [-13.89, 0.7, 11.21],
            [0.1, 0.6, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_SS01_Str_wal04",
            [-13.89, 1.7, 11.21],
            [0.1, 0.6, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_SS01_Tmp_wal05",
            [-14.05, 1.2, 11.21],
            [0.1, 0.6, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_SS01_Tmp_wal06",
            [-13.89, 1.2, 11.21],
            [0.1, 0.6, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_SS01_Str_thk01",
            [-13.75, 0.8, 11.21],
            [0.1, 0.6, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_SS01_Str_thk02",
            [-13.75, 1.91, 11.21],
            [0.1, 0.6, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_SS01_Str_thk03",
            [-13.18, 0.8, 11.21],
            [0.1, 0.6, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_SS01_Str_thk04",
            [-13.18, 1.77, 11.21],
            [0.1, 0.6, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_SS01_Tmp_thk05",
            [-13.75, 1.0, 11.21],
            [0.1, 0.6, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_SS01_Tmp_thk06",
            [-13.18, 1.0, 11.21],
            [0.1, 0.6, 0.3]
          )}
        </group>
      </scene>
    </group>
  );
}
