/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import React, { useEffect } from "react";
import { useLoader, useThree } from "react-three-fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { renderSensor } from "./utils";

export default function BasementModel(props) {
  const { camera } = useThree();

  const context = useLoader(
    GLTFLoader,
    "http://129.169.72.175/static/models/basement-context.glb"
  );

  useEffect(() => {
    camera.zoom = props.zoom;
    camera.updateProjectionMatrix();
  }, [props.zoom]);

  return (
    <group {...props} dispose={null}>
      <scene name="Scene">
        {props.showContext ? (
          <group name="Z_UP">
            <mesh
              geometry={context.nodes["0aOA0Goyb51O9g4ENGh6mQ"].geometry}
              name="0aOA0Goyb51O9g4ENGh6mQ"
              position={[15, 2, 18]}
              rotation={[-Math.PI, 0, -Math.PI]}
            >
              <meshBasicMaterial
                attach="material"
                color={"grey"}
                transparent={true}
                opacity={0.4}
              />
            </mesh>
          </group>
        ) : null}
        <group name="Raft sensors" position={[-8.1, 0, -4]}>
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot08",
            [5.5, -0.7, 8.4],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot09",
            [5.5, -0.7, 9.45],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot10",
            [5.5, -0.7, 10.5],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot11",
            [5.5, -0.7, 11.55],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot12",
            [5.5, -0.7, 12.6],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot13",
            [5.5, -0.7, 13.65],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot14",
            [5.5, -0.7, 14.7],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot15",
            [5.5, -0.7, 15.75],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot16",
            [5.5, -0.7, 16.8],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot17",
            [5.5, -0.7, 17.85],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top01",
            [5.5, 1.9, 1.05],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top02",
            [5.5, 1.9, 2.1],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top03",
            [5.5, 1.9, 3.15],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top04",
            [5.5, 1.9, 4.2],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top05",
            [5.5, 1.9, 5.25],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top06",
            [5.5, 1.9, 6.3],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top07",
            [5.5, 1.9, 7.35],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top08",
            [5.5, 1.9, 8.4],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot01",
            [5.5, -0.7, 1.05],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top09",
            [5.5, 1.9, 9.45],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot02",
            [5.5, -0.7, 2.1],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top10",
            [5.5, 1.9, 10.5],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot03",
            [5.5, -0.7, 3.15],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top11",
            [5.5, 1.9, 11.55],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot04",
            [5.5, -0.7, 4.2],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top12",
            [5.5, 1.9, 12.6],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot05",
            [5.5, -0.7, 5.25],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top13",
            [5.5, 1.9, 13.65],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot06",
            [5.5, -0.7, 6.3],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top14",
            [5.5, 1.9, 14.7],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot07",
            [5.5, -0.7, 7.35],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot18",
            [5.5, -0.7, 18.9],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot19",
            [5.5, -0.7, 19.95],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_bot20",
            [5.5, -0.7, 21.0],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top15",
            [5.5, 1.9, 15.75],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top16",
            [5.5, 1.9, 16.8],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot01",
            [0.9928571428571429, -0.7, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot02",
            [1.9857142857142858, -0.7, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot03",
            [2.9785714285714286, -0.7, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot04",
            [3.9714285714285715, -0.7, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot05",
            [4.964285714285714, -0.7, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot06",
            [5.957142857142857, -0.7, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot07",
            [6.95, -0.7, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot08",
            [7.942857142857143, -0.7, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot09",
            [8.935714285714287, -0.7, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot10",
            [9.928571428571429, -0.7, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot11",
            [10.921428571428573, -0.7, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot12",
            [11.914285714285715, -0.7, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot13",
            [12.907142857142858, -0.7, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_bot14",
            [13.9, -0.7, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top01",
            [0.9928571428571429, 1.9, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top02",
            [1.9857142857142858, 1.9, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top03",
            [2.9785714285714286, 1.9, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top04",
            [3.9714285714285715, 1.9, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top05",
            [4.964285714285714, 1.9, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top06",
            [5.957142857142857, 1.9, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top07",
            [6.95, 1.9, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top08",
            [7.942857142857143, 1.9, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top09",
            [8.935714285714287, 1.9, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top10",
            [9.928571428571429, 1.9, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top11",
            [10.921428571428573, 1.9, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top12",
            [11.914285714285715, 1.9, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top13",
            [12.907142857142858, 1.9, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_NS01_Str_top14",
            [13.9, 1.9, 10.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top17",
            [5.5, 1.9, 17.85],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top18",
            [5.5, 1.9, 18.9],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top19",
            [5.5, 1.9, 19.95],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Str_top20",
            [5.5, 1.9, 21.0],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Tmp_bot03",
            [5.5, -0.7, 3.15],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Tmp_top01",
            [5.5, 1.9, 1.05],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Tmp_top02",
            [5.5, 1.9, 2.1],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "BA_FBG_EW01_Tmp_top03",
            [5.5, 1.9, 3.15],
            [0.3, 0.1, 0.6]
          )}
        </group>
      </scene>
    </group>
  );
}
