/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import React, { useRef } from "react";
import { useLoader } from "react-three-fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { renderSensorColour } from "./utils";

export default function SteelFrame(props) {
  const group = useRef();

  const [{ nodes, materials }, context] = useLoader(GLTFLoader, [
    "http://192.168.1.253:8000/steel-frame.glb",
    "http://192.168.1.253:8000/steel-frame-context.glb", // Local static file server
  ]);

  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="Scene">
        {props.showContext ? (
          <mesh
            geometry={context.nodes.rest_of_frame.geometry}
            name="rest_of_frame"
            position={[0, 2.77, 0.06]}
            rotation={[Math.PI / 2, 0, -0.23]}
          >
            <meshBasicMaterial
              attach="material"
              color={"grey"}
              transparent={true}
              opacity={0.4}
            />
          </mesh>
        ) : null}
        <group name="Z_UP">
          <group
            name="Origin"
            position={[1.35, -22.88, props.showContext ? -3.82 : 11.68]}
          >
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.115"]
              }
              geometry={
                nodes["product-116f84ce-3b41-41a1-83ca-cc072bc2c915-body"]
                  .geometry
              }
              name="product-116f84ce-3b41-41a1-83ca-cc072bc2c915-body"
              position={[-11.24, 28.65, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.110"]
              }
              geometry={
                nodes["product-1598382f-2b87-4119-a328-b074e819a9bd-body"]
                  .geometry
              }
              name="product-1598382f-2b87-4119-a328-b074e819a9bd-body"
              position={[-17.42, 20.18, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.109"]
              }
              geometry={
                nodes["product-15cda0b2-009e-4160-be6d-14a04bd35aa8-body"]
                  .geometry
              }
              name="product-15cda0b2-009e-4160-be6d-14a04bd35aa8-body"
              position={[-17.58, 0, -11.7]}
              rotation={[0, 1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.109"]
              }
              geometry={
                nodes["product-19fe3421-9869-4409-bb85-8b899760ee2d-body"]
                  .geometry
              }
              name="product-19fe3421-9869-4409-bb85-8b899760ee2d-body"
              position={[14.49, 0, -11.7]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.109"]
              }
              geometry={
                nodes["product-28bc9b62-7e62-4936-9af2-2cc9048b10d1-body"]
                  .geometry
              }
              name="product-28bc9b62-7e62-4936-9af2-2cc9048b10d1-body"
              position={[4.02, 0, -11.7]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.109"]
              }
              geometry={
                nodes["product-28bc9b62-7e62-4936-9af2-2cc9048b10d7-body"]
                  .geometry
              }
              name="product-28bc9b62-7e62-4936-9af2-2cc9048b10d7-body"
              position={[-7.11, 0, -11.7]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              geometry={
                nodes["product-15cda0b2-009e-4160-be6d-14a04bd35b2f-body"]
                  .geometry
              }
              name="product-15cda0b2-009e-4160-be6d-14a04bd35b2f-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D6_2b")}
            </mesh>
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.114"]
              }
              geometry={
                nodes["product-19fe3421-9869-4409-bb85-8b899760eb4b-body"]
                  .geometry
              }
              name="product-19fe3421-9869-4409-bb85-8b899760eb4b-body"
              position={[14.49, 0, -11.7]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.114"]
              }
              geometry={
                nodes["product-19fe3421-9869-4409-bb85-8b899760ef0c-body"]
                  .geometry
              }
              name="product-19fe3421-9869-4409-bb85-8b899760ef0c-body"
              position={[14.49, 0, -11.7]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.112"]
              }
              geometry={
                nodes["product-225cc49a-680c-4cb5-884d-4633c6178939-body"]
                  .geometry
              }
              name="product-225cc49a-680c-4cb5-884d-4633c6178939-body"
              position={[4.02, 20.18, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.113"]
              }
              geometry={
                nodes["product-225cc49a-680c-4cb5-884d-4633c61789d3-body"]
                  .geometry
              }
              name="product-225cc49a-680c-4cb5-884d-4633c61789d3-body"
              position={[13.25, 20.18, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.104"]
              }
              geometry={
                nodes["product-22777b8f-d59d-4b43-8cea-93a3f98d294a-body"]
                  .geometry
              }
              name="product-22777b8f-d59d-4b43-8cea-93a3f98d294a-body"
              position={[-17.58, 0, -11.7]}
              rotation={[0, 1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.104"]
              }
              geometry={
                nodes["product-28bc9b62-7e62-4936-9af2-2cc9048b136d-body"]
                  .geometry
              }
              name="product-28bc9b62-7e62-4936-9af2-2cc9048b136d-body"
              position={[14.49, 0, -11.7]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.104"]
              }
              geometry={
                nodes["product-28bc9b62-7e62-4936-9af2-2cc9048b13e8-body"]
                  .geometry
              }
              name="product-28bc9b62-7e62-4936-9af2-2cc9048b13e8-body"
              position={[4.02, 0, -11.7]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.104"]
              }
              geometry={
                nodes["product-519fc3df-70f6-4203-87a2-2911afdf71a5-body"]
                  .geometry
              }
              name="product-519fc3df-70f6-4203-87a2-2911afdf71a5-body"
              position={[-7.11, 0, -11.7]}
              rotation={[0, 1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.108"]
              }
              geometry={
                nodes["product-28bc9b62-7e62-4936-9af2-2cc9048b10b4-body"]
                  .geometry
              }
              name="product-28bc9b62-7e62-4936-9af2-2cc9048b10b4-body"
              position={[14.49, 0, -11.7]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.108"]
              }
              geometry={
                nodes["product-28bc9b62-7e62-4936-9af2-2cc9048b10b8-body"]
                  .geometry
              }
              name="product-28bc9b62-7e62-4936-9af2-2cc9048b10b8-body"
              position={[-7.11, 0, -11.7]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.108"]
              }
              geometry={
                nodes["product-28bc9b62-7e62-4936-9af2-2cc9048b10ba-body"]
                  .geometry
              }
              name="product-28bc9b62-7e62-4936-9af2-2cc9048b10ba-body"
              position={[4.02, 0, -11.7]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.108"]
              }
              geometry={
                nodes["product-28bc9b62-7e62-4936-9af2-2cc9048b10be-body"]
                  .geometry
              }
              name="product-28bc9b62-7e62-4936-9af2-2cc9048b10be-body"
              position={[-17.58, 0, -11.7]}
              rotation={[0, 1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.108"]
              }
              geometry={
                nodes["product-f618639d-9e5a-4239-86d6-e00f73264263-body"]
                  .geometry
              }
              name="product-f618639d-9e5a-4239-86d6-e00f73264263-body"
              position={[-17.58, 0, -11.7]}
              rotation={[0, 1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.106"]
              }
              geometry={
                nodes["product-28bc9b62-7e62-4936-9af2-2cc9048b1121-body"]
                  .geometry
              }
              name="product-28bc9b62-7e62-4936-9af2-2cc9048b1121-body"
              position={[14.49, 0, -11.7]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.106"]
              }
              geometry={
                nodes["product-28bc9b62-7e62-4936-9af2-2cc9048b1125-body"]
                  .geometry
              }
              name="product-28bc9b62-7e62-4936-9af2-2cc9048b1125-body"
              position={[-7.11, 0, -11.7]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.106"]
              }
              geometry={
                nodes["product-28bc9b62-7e62-4936-9af2-2cc9048b1127-body"]
                  .geometry
              }
              name="product-28bc9b62-7e62-4936-9af2-2cc9048b1127-body"
              position={[4.02, 0, -11.7]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.106"]
              }
              geometry={
                nodes["product-28bc9b62-7e62-4936-9af2-2cc9048b112b-body"]
                  .geometry
              }
              name="product-28bc9b62-7e62-4936-9af2-2cc9048b112b-body"
              position={[-17.58, 0, -11.7]}
              rotation={[0, 1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.107"]
              }
              geometry={
                nodes["product-28bc9b62-7e62-4936-9af2-2cc9048b1165-body"]
                  .geometry
              }
              name="product-28bc9b62-7e62-4936-9af2-2cc9048b1165-body"
              position={[14.49, 0, -11.7]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.107"]
              }
              geometry={
                nodes["product-28bc9b62-7e62-4936-9af2-2cc9048b1169-body"]
                  .geometry
              }
              name="product-28bc9b62-7e62-4936-9af2-2cc9048b1169-body"
              position={[-7.11, 0, -11.7]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.107"]
              }
              geometry={
                nodes["product-28bc9b62-7e62-4936-9af2-2cc9048b116b-body"]
                  .geometry
              }
              name="product-28bc9b62-7e62-4936-9af2-2cc9048b116b-body"
              position={[4.02, 0, -11.7]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.107"]
              }
              geometry={
                nodes["product-28bc9b62-7e62-4936-9af2-2cc9048b116f-body"]
                  .geometry
              }
              name="product-28bc9b62-7e62-4936-9af2-2cc9048b116f-body"
              position={[-17.58, 0, -11.7]}
              rotation={[0, 1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.105"]
              }
              geometry={
                nodes["product-28bc9b62-7e62-4936-9af2-2cc9048b11e9-body"]
                  .geometry
              }
              name="product-28bc9b62-7e62-4936-9af2-2cc9048b11e9-body"
              position={[4.02, 0, -11.7]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.105"]
              }
              geometry={
                nodes["product-28bc9b62-7e62-4936-9af2-2cc9048b11eb-body"]
                  .geometry
              }
              name="product-28bc9b62-7e62-4936-9af2-2cc9048b11eb-body"
              position={[14.49, 0, -11.7]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.105"]
              }
              geometry={
                nodes["product-28bc9b62-7e62-4936-9af2-2cc9048b11ed-body"]
                  .geometry
              }
              name="product-28bc9b62-7e62-4936-9af2-2cc9048b11ed-body"
              position={[-17.58, 0, -11.7]}
              rotation={[0, 1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.105"]
              }
              geometry={
                nodes["product-519fc3df-70f6-4203-87a2-2911afdf70f1-body"]
                  .geometry
              }
              name="product-519fc3df-70f6-4203-87a2-2911afdf70f1-body"
              position={[-7.11, 0, -11.7]}
              rotation={[0, 1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.136"]
              }
              geometry={
                nodes["product-519fc3df-70f6-4203-87a2-2911afdf7589-body"]
                  .geometry
              }
              name="product-519fc3df-70f6-4203-87a2-2911afdf7589-body"
              position={[-6.94, 20.18, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.135"]
              }
              geometry={
                nodes["product-519fc3df-70f6-4203-87a2-2911afdf75b8-body"]
                  .geometry
              }
              name="product-519fc3df-70f6-4203-87a2-2911afdf75b8-body"
              position={[-10.99, 20.18, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.137"]
              }
              geometry={
                nodes["product-519fc3df-70f6-4203-87a2-2911afdf76a3-body"]
                  .geometry
              }
              name="product-519fc3df-70f6-4203-87a2-2911afdf76a3-body"
              position={[4.02, 0, -11.7]}
              rotation={[0, 1.57, 0]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.120"]
              }
              geometry={
                nodes["product-5213039d-f391-404d-af12-b987f72c9282-body"]
                  .geometry
              }
              name="product-5213039d-f391-404d-af12-b987f72c9282-body"
              position={[3.86, 20.18, -11.7]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={
                nodes["product-5213039d-f391-404d-af12-b987f72c92e0-body"]
                  .geometry
              }
              name="product-5213039d-f391-404d-af12-b987f72c92e0-body"
              position={[0.01, 24.68, -11.7]}
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_BM_D34_2a")}
            </mesh>
            <mesh
              geometry={
                nodes["product-a2982c51-d74f-46df-8ed4-0ea86dd5902b-body"]
                  .geometry
              }
              name="product-a2982c51-d74f-46df-8ed4-0ea86dd5902b-body"
              position={[-11.59, 24.68, -11.7]}
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_BM_D46_2b")}
            </mesh>
            <mesh
              geometry={
                nodes["product-a2982c51-d74f-46df-8ed4-0ea86dd59080-body"]
                  .geometry
              }
              name="product-a2982c51-d74f-46df-8ed4-0ea86dd59080-body"
              position={[10.7, 24.68, -11.7]}
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_BM_D13_2b")}
            </mesh>
            <mesh
              geometry={
                nodes["product-a2982c51-d74f-46df-8ed4-0ea86dd590db-body"]
                  .geometry
              }
              name="product-a2982c51-d74f-46df-8ed4-0ea86dd590db-body"
              position={[0.01, 24.68, -11.7]}
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_BM_D34_2b")}
            </mesh>
            <mesh
              geometry={
                nodes["product-a2982c51-d74f-46df-8ed4-0ea86dd598cd-body"]
                  .geometry
              }
              name="product-a2982c51-d74f-46df-8ed4-0ea86dd598cd-body"
              position={[-11.59, 20.18, -11.7]}
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_BM_D46_1b")}
            </mesh>
            <mesh
              geometry={
                nodes["product-a2982c51-d74f-46df-8ed4-0ea86dd5990a-body"]
                  .geometry
              }
              name="product-a2982c51-d74f-46df-8ed4-0ea86dd5990a-body"
              position={[0.01, 20.18, -11.7]}
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_BM_D34_1a")}
            </mesh>
            <mesh
              geometry={
                nodes["product-a2982c51-d74f-46df-8ed4-0ea86dd59969-body"]
                  .geometry
              }
              name="product-a2982c51-d74f-46df-8ed4-0ea86dd59969-body"
              position={[-11.59, 20.18, -11.7]}
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_BM_D46_1a")}
            </mesh>
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.146"]
              }
              geometry={
                nodes["product-a2982c51-d74f-46df-8ed4-0ea86dd59a52-body"]
                  .geometry
              }
              name="product-a2982c51-d74f-46df-8ed4-0ea86dd59a52-body"
              position={[-11.59, 20.18, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.147"]
              }
              geometry={
                nodes["product-a2982c51-d74f-46df-8ed4-0ea86dd59ae9-body"]
                  .geometry
              }
              name="product-a2982c51-d74f-46df-8ed4-0ea86dd59ae9-body"
              position={[-11.59, 20.18, -11.7]}
            />
            <mesh
              geometry={
                nodes["product-a2982c51-d74f-46df-8ed4-0ea86dd59b42-body"]
                  .geometry
              }
              name="product-a2982c51-d74f-46df-8ed4-0ea86dd59b42-body"
              position={[11.3, 20.18, -11.7]}
              rotation={[-Math.PI, 0, -Math.PI]}
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_BM_D13_1b")}
            </mesh>
            <mesh
              geometry={
                nodes["product-a2982c51-d74f-46df-8ed4-0ea86dd59c8c-body"]
                  .geometry
              }
              name="product-a2982c51-d74f-46df-8ed4-0ea86dd59c8c-body"
              position={[0.01, 20.18, -11.7]}
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_BM_D34_1b")}
            </mesh>
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.142"]
              }
              geometry={
                nodes["product-a2982c51-d74f-46df-8ed4-0ea86dd59d29-body"]
                  .geometry
              }
              name="product-a2982c51-d74f-46df-8ed4-0ea86dd59d29-body"
              position={[0.01, 20.18, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.143"]
              }
              geometry={
                nodes["product-a2982c51-d74f-46df-8ed4-0ea86dd59dca-body"]
                  .geometry
              }
              name="product-a2982c51-d74f-46df-8ed4-0ea86dd59dca-body"
              position={[10.7, 20.18, -11.7]}
            />
            <mesh
              geometry={
                nodes["product-a2982c51-d74f-46df-8ed4-0ea86dd59ea3-body"]
                  .geometry
              }
              name="product-a2982c51-d74f-46df-8ed4-0ea86dd59ea3-body"
              position={[11.3, 20.18, -11.7]}
              rotation={[-Math.PI, 0, -Math.PI]}
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_BM_D13_1a")}
            </mesh>
            <mesh
              geometry={
                nodes["product-ad87a8f9-6ece-4c8f-b36d-a863da0d4867-body"]
                  .geometry
              }
              name="product-ad87a8f9-6ece-4c8f-b36d-a863da0d4867-body"
              position={[-11.59, 28.65, -11.7]}
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_BM_D46_3b")}
            </mesh>
            <mesh
              geometry={
                nodes["product-ad87a8f9-6ece-4c8f-b36d-a863da0d4880-body"]
                  .geometry
              }
              name="product-ad87a8f9-6ece-4c8f-b36d-a863da0d4880-body"
              position={[-11.59, 24.68, -11.7]}
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_BM_D46_2a")}
            </mesh>
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.126"]
              }
              geometry={
                nodes["product-ad87a8f9-6ece-4c8f-b36d-a863da0d49cd-body"]
                  .geometry
              }
              name="product-ad87a8f9-6ece-4c8f-b36d-a863da0d49cd-body"
              position={[10.7, 28.65, -11.7]}
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_BM_D13_3b")}
            </mesh>
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.124"]
              }
              geometry={
                nodes["product-ad87a8f9-6ece-4c8f-b36d-a863da0d4a03-body"]
                  .geometry
              }
              name="product-ad87a8f9-6ece-4c8f-b36d-a863da0d4a03-body"
              position={[-11.59, 28.65, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.125"]
              }
              geometry={
                nodes["product-ad87a8f9-6ece-4c8f-b36d-a863da0d4ac2-body"]
                  .geometry
              }
              name="product-ad87a8f9-6ece-4c8f-b36d-a863da0d4ac2-body"
              position={[10.7, 28.65, -11.7]}
            />
            <mesh
              geometry={
                nodes["product-ad87a8f9-6ece-4c8f-b36d-a863da0d4b99-body"]
                  .geometry
              }
              name="product-ad87a8f9-6ece-4c8f-b36d-a863da0d4b99-body"
              position={[10.7, 28.65, -11.7]}
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_BM_D13_3a")}
            </mesh>
            <mesh
              geometry={
                nodes["product-ad87a8f9-6ece-4c8f-b36d-a863da0d4bc5-body"]
                  .geometry
              }
              name="product-ad87a8f9-6ece-4c8f-b36d-a863da0d4bc5-body"
              position={[-11.59, 28.65, -11.7]}
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_BM_D46_3a")}
            </mesh>
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.134"]
              }
              geometry={
                nodes["product-ad87a8f9-6ece-4c8f-b36d-a863da0d4d41-body"]
                  .geometry
              }
              name="product-ad87a8f9-6ece-4c8f-b36d-a863da0d4d41-body"
              position={[0.01, 24.68, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.133"]
              }
              geometry={
                nodes["product-ad87a8f9-6ece-4c8f-b36d-a863da0d4e89-body"]
                  .geometry
              }
              name="product-ad87a8f9-6ece-4c8f-b36d-a863da0d4e89-body"
              position={[-11.59, 24.68, -11.7]}
            />
            <mesh
              geometry={
                nodes["product-ad87a8f9-6ece-4c8f-b36d-a863da0d4f7c-body"]
                  .geometry
              }
              name="product-ad87a8f9-6ece-4c8f-b36d-a863da0d4f7c-body"
              position={[10.7, 24.68, -11.7]}
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_BM_D13_2a")}
            </mesh>
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.132"]
              }
              geometry={
                nodes["product-ad87a8f9-6ece-4c8f-b36d-a863da0d4f96-body"]
                  .geometry
              }
              name="product-ad87a8f9-6ece-4c8f-b36d-a863da0d4f96-body"
              position={[10.7, 24.68, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.131"]
              }
              geometry={
                nodes["product-ad87a8f9-6ece-4c8f-b36d-a863da0d4fb4-body"]
                  .geometry
              }
              name="product-ad87a8f9-6ece-4c8f-b36d-a863da0d4fb4-body"
              position={[0.01, 24.68, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.130"]
              }
              geometry={
                nodes["product-ad87a8f9-6ece-4c8f-b36d-a863da0d4fc4-body"]
                  .geometry
              }
              name="product-ad87a8f9-6ece-4c8f-b36d-a863da0d4fc4-body"
              position={[-11.59, 24.68, -11.7]}
            />
            <mesh
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db439-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db439-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D1_1b")}
            </mesh>
            <mesh
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db459-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db459-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D1_0b")}
            </mesh>
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.175"]
              }
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db464-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db464-body"
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.176"]
              }
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db4b2-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db4b2-body"
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.177"]
              }
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db4c3-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db4c3-body"
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.178"]
              }
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db515-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db515-body"
            />
            <mesh
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db527-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db527-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D4_1a")}
            </mesh>
            <mesh
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db546-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db546-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D3_1a")}
            </mesh>
            <mesh
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db579-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db579-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D1_1a")}
            </mesh>
            <mesh
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db598-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db598-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D1_0a")}
            </mesh>
            <mesh
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db5a5-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db5a5-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D3_0a")}
            </mesh>
            <mesh
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db5cd-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db5cd-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D4_0a")}
            </mesh>
            <mesh
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db5eb-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db5eb-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D6_0a")}
            </mesh>
            <mesh
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db658-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db658-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D6_1b")}
            </mesh>
            <mesh
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db66c-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db66c-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D6_1a")}
            </mesh>
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.164"]
              }
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db688-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db688-body"
            />
            <mesh
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db6fd-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db6fd-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D4_1b")}
            </mesh>
            <mesh
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db71e-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db71e-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D3_1b")}
            </mesh>
            <mesh
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db73d-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db73d-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D3_0b")}
            </mesh>
            <mesh
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db747-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db747-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D4_0b")}
            </mesh>
            <mesh
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db778-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db778-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D6_0b")}
            </mesh>
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.170"]
              }
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db78c-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db78c-body"
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.171"]
              }
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db7de-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db7de-body"
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.172"]
              }
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db7ea-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db7ea-body"
            />
            <mesh
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db8e1-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db8e1-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D4_2a")}
            </mesh>
            <mesh
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db8f0-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db8f0-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D6_2a")}
            </mesh>
            <mesh
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db905-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db905-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D1_2a")}
            </mesh>
            <mesh
              geometry={
                nodes["product-c1534c89-e96b-493f-a16d-77ccdd9db913-body"]
                  .geometry
              }
              name="product-c1534c89-e96b-493f-a16d-77ccdd9db913-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D3_2a")}
            </mesh>
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.111"]
              }
              geometry={
                nodes["product-d684b3f8-6d2f-40a1-ad25-cbda66e89018-body"]
                  .geometry
              }
              name="product-d684b3f8-6d2f-40a1-ad25-cbda66e89018-body"
              position={[14.32, 28.65, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.102"]
              }
              geometry={
                nodes["product-db8e96e7-1b07-4ce3-9cbe-ad5b2a877e26-body"]
                  .geometry
              }
              name="product-db8e96e7-1b07-4ce3-9cbe-ad5b2a877e26-body"
              position={[3.86, 28.65, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.101"]
              }
              geometry={
                nodes["product-db8e96e7-1b07-4ce3-9cbe-ad5b2a877e35-body"]
                  .geometry
              }
              name="product-db8e96e7-1b07-4ce3-9cbe-ad5b2a877e35-body"
              position={[-1.54, 28.65, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.099"]
              }
              geometry={
                nodes["product-db8e96e7-1b07-4ce3-9cbe-ad5b2a877e46-body"]
                  .geometry
              }
              name="product-db8e96e7-1b07-4ce3-9cbe-ad5b2a877e46-body"
              position={[-17.74, 28.65, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.100"]
              }
              geometry={
                nodes["product-db8e96e7-1b07-4ce3-9cbe-ad5b2a877e6f-body"]
                  .geometry
              }
              name="product-db8e96e7-1b07-4ce3-9cbe-ad5b2a877e6f-body"
              position={[-6.94, 28.65, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.097"]
              }
              geometry={
                nodes["product-db8e96e7-1b07-4ce3-9cbe-ad5b2a877e8b-body"]
                  .geometry
              }
              name="product-db8e96e7-1b07-4ce3-9cbe-ad5b2a877e8b-body"
              position={[3.86, 24.68, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.096"]
              }
              geometry={
                nodes["product-db8e96e7-1b07-4ce3-9cbe-ad5b2a877e9e-body"]
                  .geometry
              }
              name="product-db8e96e7-1b07-4ce3-9cbe-ad5b2a877e9e-body"
              position={[-1.54, 24.68, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.098"]
              }
              geometry={
                nodes["product-db8e96e7-1b07-4ce3-9cbe-ad5b2a877ea4-body"]
                  .geometry
              }
              name="product-db8e96e7-1b07-4ce3-9cbe-ad5b2a877ea4-body"
              position={[9.26, 24.68, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.093"]
              }
              geometry={
                nodes["product-db8e96e7-1b07-4ce3-9cbe-ad5b2a877ede-body"]
                  .geometry
              }
              name="product-db8e96e7-1b07-4ce3-9cbe-ad5b2a877ede-body"
              position={[-17.74, 24.68, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.095"]
              }
              geometry={
                nodes["product-db8e96e7-1b07-4ce3-9cbe-ad5b2a877eed-body"]
                  .geometry
              }
              name="product-db8e96e7-1b07-4ce3-9cbe-ad5b2a877eed-body"
              position={[-6.94, 24.68, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.094"]
              }
              geometry={
                nodes["product-db8e96e7-1b07-4ce3-9cbe-ad5b2a877ef3-body"]
                  .geometry
              }
              name="product-db8e96e7-1b07-4ce3-9cbe-ad5b2a877ef3-body"
              position={[-12.34, 24.68, -11.7]}
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.103"]
              }
              geometry={
                nodes["product-db8e96e7-1b07-4ce3-9cbe-ad5b2a877fd3-body"]
                  .geometry
              }
              name="product-db8e96e7-1b07-4ce3-9cbe-ad5b2a877fd3-body"
              position={[9.26, 28.65, -11.7]}
            />
            <mesh
              geometry={
                nodes["product-eb13113c-8987-444f-acc1-93dbd4879d29-body"]
                  .geometry
              }
              name="product-eb13113c-8987-444f-acc1-93dbd4879d29-body"
              position={[0.01, 28.65, -11.7]}
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_BM_D34_3a")}
            </mesh>
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.117"]
              }
              geometry={
                nodes["product-eb13113c-8987-444f-acc1-93dbd4879d9a-body"]
                  .geometry
              }
              name="product-eb13113c-8987-444f-acc1-93dbd4879d9a-body"
              position={[0.01, 28.65, -11.7]}
            />
            <mesh
              geometry={
                nodes["product-eb13113c-8987-444f-acc1-93dbd487a2dc-body"]
                  .geometry
              }
              name="product-eb13113c-8987-444f-acc1-93dbd487a2dc-body"
              position={[0.01, 28.65, -11.7]}
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_BM_D34_3b")}
            </mesh>
            <mesh
              geometry={
                nodes["product-f618639d-9e5a-4239-86d6-e00f7326421d-body"]
                  .geometry
              }
              name="product-f618639d-9e5a-4239-86d6-e00f7326421d-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D3_2b")}
            </mesh>
            <mesh
              geometry={
                nodes["product-f618639d-9e5a-4239-86d6-e00f73264301-body"]
                  .geometry
              }
              name="product-f618639d-9e5a-4239-86d6-e00f73264301-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D4_2b")}
            </mesh>
            <mesh
              geometry={
                nodes["product-f618639d-9e5a-4239-86d6-e00f7326437b-body"]
                  .geometry
              }
              name="product-f618639d-9e5a-4239-86d6-e00f7326437b-body"
            >
              {renderSensorColour(props.sensorColours, "FR_FBG_CL_D1_2b")}
            </mesh>
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.157"]
              }
              geometry={
                nodes["product-f618639d-9e5a-4239-86d6-e00f73264547-body"]
                  .geometry
              }
              name="product-f618639d-9e5a-4239-86d6-e00f73264547-body"
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.156"]
              }
              geometry={
                nodes["product-f618639d-9e5a-4239-86d6-e00f7326454a-body"]
                  .geometry
              }
              name="product-f618639d-9e5a-4239-86d6-e00f7326454a-body"
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.154"]
              }
              geometry={
                nodes["product-f618639d-9e5a-4239-86d6-e00f7326456d-body"]
                  .geometry
              }
              name="product-f618639d-9e5a-4239-86d6-e00f7326456d-body"
            />
            <mesh
              material={
                materials["surface-style-196-metal---steel-43-275-fx.155"]
              }
              geometry={
                nodes["product-f618639d-9e5a-4239-86d6-e00f73264579-body"]
                  .geometry
              }
              name="product-f618639d-9e5a-4239-86d6-e00f73264579-body"
            />
          </group>
        </group>
      </scene>
    </group>
  );
}
