/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import React, { useEffect } from "react";
import { useLoader, useThree } from "react-three-fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { renderSensor } from "./utils";

export default function StrongFloorModel(props) {
  const { camera } = useThree();

  const [{ nodes }, context] = useLoader(GLTFLoader, [
    "http://129.169.72.175/static/models/strong-floor.glb",
    "http://129.169.72.175/static/models/strong-floor-context.glb",
  ]);

  useEffect(() => {
    camera.zoom = props.zoom;
    camera.updateProjectionMatrix();
  }, [props.zoom]);

  return (
    <group {...props} dispose={null}>
      <scene name="Scene">
        {props.showContext ? (
          <group name="Z_UP" position={[-10, 0, 5]}>
            <mesh
              geometry={context.nodes["01rx$$eeIoIf75A6kFjQLz"].geometry}
              name="01rx$$eeIoIf75A6kFjQLz"
            >
              <meshBasicMaterial
                attach="material"
                color={"grey"}
                transparent={true}
                opacity={0.4}
              />
            </mesh>
          </group>
        ) : null}
        <group name="Z_UP" position={[-10, 0, 5]}>
          <mesh
            material={nodes["04iyR6e2lqJuxunywB_437"].material}
            geometry={nodes["04iyR6e2lqJuxunywB_437"].geometry}
            name="04iyR6e2lqJuxunywB_437"
          />
        </group>
        <group name="Sensors" position={[-10, 0, -5]}>
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_bot01",
            [0.51, 0.04, 2.35],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_bot02",
            [1.51, 0.04, 2.35],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_bot03",
            [2.51, 0.04, 2.35],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_bot04",
            [3.51, 0.04, 2.35],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_bot05",
            [4.51, 0.04, 2.35],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_bot06",
            [5.51, 0.04, 2.35],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_bot07",
            [6.51, 0.04, 2.35],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_bot08",
            [7.51, 0.04, 2.35],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_bot09",
            [8.51, 0.04, 2.35],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_bot10",
            [9.51, 0.04, 2.35],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_bot11",
            [10.43, 0.04, 2.35],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_bot12",
            [11.43, 0.04, 2.35],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_bot13",
            [12.43, 0.04, 2.35],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_bot14",
            [13.43, 0.04, 2.35],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_bot15",
            [14.43, 0.04, 2.35],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_bot16",
            [15.43, 0.04, 2.35],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_bot17",
            [16.39, 0.04, 2.35],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_bot18",
            [17.36, 0.04, 2.35],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_bot19",
            [18.36, 0.04, 2.35],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_bot20",
            [19.36, 0.04, 2.35],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_bot01",
            [0.51, 0.04, 5.12],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_bot02",
            [1.51, 0.04, 5.12],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_bot03",
            [2.51, 0.04, 5.12],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_bot04",
            [3.51, 0.04, 5.12],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_bot05",
            [4.51, 0.04, 5.12],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_bot06",
            [5.51, 0.04, 5.12],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_bot07",
            [6.51, 0.04, 5.12],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_bot08",
            [7.51, 0.04, 5.12],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_bot09",
            [8.51, 0.04, 5.12],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_bot10",
            [9.51, 0.04, 5.12],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_bot11",
            [10.44, 0.04, 5.12],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_bot12",
            [11.44, 0.04, 5.12],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_bot13",
            [12.44, 0.04, 5.12],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_bot14",
            [13.44, 0.04, 5.12],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_bot15",
            [14.44, 0.04, 5.12],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_bot16",
            [15.44, 0.04, 5.12],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_bot17",
            [16.44, 0.04, 5.12],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_bot18",
            [17.44, 0.04, 5.12],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_bot19",
            [18.44, 0.04, 5.12],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_bot20",
            [19.44, 0.04, 5.12],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_bot01",
            [0.51, 0.04, 7.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_bot02",
            [1.51, 0.04, 7.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_bot03",
            [2.51, 0.04, 7.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_bot04",
            [3.51, 0.04, 7.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_bot05",
            [4.51, 0.04, 7.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_bot06",
            [5.51, 0.04, 7.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_bot07",
            [6.51, 0.04, 7.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_bot08",
            [7.51, 0.04, 7.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_bot09",
            [8.51, 0.04, 7.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_bot10",
            [9.51, 0.04, 7.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_bot11",
            [10.38, 0.04, 7.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_bot12",
            [11.38, 0.04, 7.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_bot13",
            [12.38, 0.04, 7.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_bot14",
            [13.38, 0.04, 7.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_bot15",
            [14.38, 0.04, 7.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_bot16",
            [15.38, 0.04, 7.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_bot17",
            [16.38, 0.04, 7.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_bot18",
            [17.38, 0.04, 7.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_bot19",
            [18.38, 0.04, 7.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_bot20",
            [19.38, 0.04, 7.5],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_top01",
            [0.58, 0.96, 2.53],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_top02",
            [1.58, 0.96, 2.53],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_top03",
            [2.58, 0.96, 2.53],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_top04",
            [3.58, 0.96, 2.53],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_top05",
            [4.58, 0.96, 2.53],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_top06",
            [5.58, 0.96, 2.53],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_top07",
            [6.58, 0.96, 2.53],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_top08",
            [7.58, 0.96, 2.53],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_top09",
            [8.58, 0.96, 2.53],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_top10",
            [9.58, 0.96, 2.53],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_top11",
            [10.45, 0.96, 2.53],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_top12",
            [11.45, 0.96, 2.53],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_top13",
            [12.45, 0.96, 2.53],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_top14",
            [13.45, 0.96, 2.53],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_top15",
            [14.45, 0.96, 2.53],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_top16",
            [15.45, 0.96, 2.53],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_top17",
            [16.45, 0.96, 2.53],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_top18",
            [17.45, 0.96, 2.53],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_top19",
            [18.45, 0.96, 2.53],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW01_Str_top20",
            [19.45, 0.96, 2.53],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_top01",
            [0.52, 0.96, 4.93],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_top02",
            [1.52, 0.96, 4.93],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_top03",
            [2.52, 0.96, 4.93],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_top04",
            [3.52, 0.96, 4.93],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_top05",
            [4.52, 0.96, 4.93],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_top06",
            [5.52, 0.96, 4.93],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_top07",
            [6.52, 0.96, 4.93],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_top08",
            [7.52, 0.96, 4.93],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_top09",
            [8.52, 0.96, 4.93],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_top10",
            [9.52, 0.96, 4.93],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_top11",
            [10.38, 0.96, 4.93],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_top12",
            [11.38, 0.96, 4.93],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_top13",
            [12.38, 0.96, 4.93],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_top14",
            [13.38, 0.96, 4.93],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_top15",
            [14.38, 0.96, 4.93],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_topt16",
            [15.38, 0.96, 4.93],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_top17",
            [16.38, 0.96, 4.93],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_top18",
            [17.38, 0.96, 4.93],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_top19",
            [18.38, 0.96, 4.93],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW02_Str_top20",
            [19.38, 0.96, 4.93],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_top01",
            [0.56, 0.96, 7.32],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_top02",
            [1.56, 0.96, 7.32],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_top03",
            [2.56, 0.96, 7.32],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_top04",
            [3.56, 0.96, 7.32],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_top05",
            [4.56, 0.96, 7.32],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_top06",
            [5.56, 0.96, 7.32],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_top07",
            [6.56, 0.96, 7.32],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_top08",
            [7.56, 0.96, 7.32],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_top09",
            [8.56, 0.96, 7.32],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_top10",
            [9.56, 0.96, 7.32],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_top11",
            [10.44, 0.96, 7.32],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_top12",
            [11.44, 0.96, 7.32],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_top13",
            [12.44, 0.96, 7.32],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_top14",
            [13.44, 0.96, 7.32],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_top15",
            [14.44, 0.96, 7.32],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_top16",
            [15.44, 0.96, 7.32],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_top17",
            [16.44, 0.96, 7.32],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_top18",
            [17.44, 0.96, 7.32],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_top19",
            [18.44, 0.96, 7.32],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_EW03_Str_top20",
            [19.44, 0.96, 7.32],
            [0.6, 0.1, 0.3]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Str_bot01",
            [17.58, 0.04, 1.13],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Str_bot02",
            [17.58, 0.04, 2.13],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Str_bot03",
            [17.58, 0.04, 3.13],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Str_bot04",
            [17.58, 0.04, 4.13],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Str_bot05",
            [17.58, 0.04, 5.06],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Str_bot06",
            [17.58, 0.04, 5.99],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Str_bot07",
            [17.58, 0.04, 6.99],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Str_bot08",
            [17.58, 0.04, 7.99],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Str_bot09",
            [17.58, 0.04, 8.99],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS02_Str_bot01",
            [15.28, 0.04, 1.1],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS02_Str_bot02",
            [15.28, 0.04, 2.1],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS02_Str_bot03",
            [15.28, 0.04, 3.1],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS02_Str_bot04",
            [15.28, 0.04, 4.1],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS02_Str_bot05",
            [15.28, 0.04, 5.04],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS02_Str_bot06",
            [15.28, 0.04, 5.98],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS02_Str_bot07",
            [15.28, 0.04, 6.98],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS02_Str_bot08",
            [15.28, 0.04, 7.98],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS02_Str_bot09",
            [15.28, 0.04, 8.98],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS03_Str_bot01",
            [12.47, 0.04, 0.94],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS03_Str_bot02",
            [12.47, 0.04, 1.94],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS03_Str_bot03",
            [12.47, 0.04, 2.94],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS03_Str_bot04",
            [12.47, 0.04, 3.94],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS03_Str_bot05",
            [12.47, 0.04, 4.96],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS03_Str_bot06",
            [12.47, 0.04, 5.98],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS03_Str_bot07",
            [12.47, 0.04, 6.98],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS03_Str_bot08",
            [12.47, 0.04, 7.98],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS03_Str_bot09",
            [12.47, 0.04, 8.98],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Str_bot01",
            [9.9, 0.04, 1.0],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Str_bot02",
            [9.9, 0.04, 2.0],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Str_bot03",
            [9.9, 0.04, 3.0],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Str_bot04",
            [9.9, 0.04, 4.0],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Str_bot05",
            [9.9, 0.04, 5.03],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Str_bot06",
            [9.9, 0.04, 6.06],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Str_bot07",
            [9.9, 0.04, 7.06],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Str_bot08",
            [9.9, 0.04, 8.06],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Str_bot09",
            [9.9, 0.04, 9.06],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS05_Str_bot01",
            [7.47, 0.04, 1.03],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS05_Str_bot02",
            [7.47, 0.04, 2.03],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS05_Str_bot03",
            [7.47, 0.04, 3.03],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS05_Str_bot04",
            [7.47, 0.04, 4.03],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS05_Str_bot05",
            [7.47, 0.04, 5.02],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS05_Str_bot06",
            [7.47, 0.04, 6.01],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS05_Str_bot07",
            [7.47, 0.04, 7.01],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS05_Str_bot08",
            [7.47, 0.04, 8.01],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS05_Str_bot09",
            [7.47, 0.04, 9.01],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS06_Str_bot01",
            [5.08, 0.04, 1.01],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS06_Str_bot02",
            [5.08, 0.04, 2.01],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS06_Str_bot03",
            [5.08, 0.04, 3.01],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS06_Str_bot04",
            [5.08, 0.04, 4.01],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS06_Str_bot05",
            [5.08, 0.04, 4.97],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS06_Str_bot06",
            [5.08, 0.04, 5.93],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS06_Str_bot07",
            [5.08, 0.04, 6.93],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS06_Str_bot08",
            [5.08, 0.04, 7.93],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS06_Str_bot09",
            [5.08, 0.04, 8.93],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Str_bot01",
            [2.64, 0.04, 0.96],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Str_bot02",
            [2.64, 0.04, 1.96],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Str_bot03",
            [2.64, 0.04, 2.96],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Str_bot04",
            [2.64, 0.04, 3.96],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Str_bot05",
            [2.64, 0.04, 4.94],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Str_bot06",
            [2.64, 0.04, 5.91],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Str_bot07",
            [2.64, 0.04, 6.91],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Str_bot08",
            [2.64, 0.04, 7.91],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Str_bot09",
            [2.64, 0.04, 8.91],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Str_top01",
            [17.84, 0.96, 1.2],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Str_top02",
            [17.84, 0.96, 2.2],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Str_top03",
            [17.84, 0.96, 3.2],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Str_top04",
            [17.84, 0.96, 4.21],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Str_top05",
            [17.84, 0.96, 5.0],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Str_top06",
            [17.84, 0.96, 5.94],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Str_top07",
            [17.84, 0.96, 6.94],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Str_top08",
            [17.84, 0.96, 7.94],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Str_top09",
            [17.84, 0.96, 8.94],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS02_Str_top01",
            [15.08, 0.96, 0.93],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS02_Str_top02",
            [15.08, 0.96, 1.93],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS02_Str_top03",
            [15.08, 0.96, 2.93],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS02_Str_top04",
            [15.08, 0.96, 3.93],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS02_Str_top05",
            [15.08, 0.96, 4.94],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS02_Str_top06",
            [15.08, 0.96, 5.95],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS02_Str_top07",
            [15.08, 0.96, 6.95],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS02_Str_top08",
            [15.08, 0.96, 7.95],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS02_Str_top09",
            [15.08, 0.96, 8.95],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS03_Str_top01",
            [12.42, 0.96, 1.67],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS03_Str_top02",
            [12.42, 0.96, 2.67],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS03_Str_top03",
            [12.42, 0.96, 3.67],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS03_Str_top04",
            [12.42, 0.96, 4.67],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS03_Str_top05",
            [12.42, 0.96, 5.67],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS03_Str_top06",
            [12.42, 0.96, 6.58],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS03_Str_top08",
            [12.42, 0.96, 8.1],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS03_Str_top09",
            [12.42, 0.96, 9.1],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Str_top01",
            [10.02, 0.96, 1.08],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Str_top02",
            [10.02, 0.96, 2.08],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Str_top03",
            [10.02, 0.96, 3.08],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Str_top04",
            [10.02, 0.96, 4.08],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Str_top05",
            [10.02, 0.96, 5.06],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Str_top06",
            [10.02, 0.96, 6.03],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Str_top07",
            [10.02, 0.96, 7.03],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Str_top08",
            [10.02, 0.96, 8.03],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Str_top09",
            [10.02, 0.96, 9.03],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS05_Str_top01",
            [7.6, 0.96, 1.06],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS05_Str_top02",
            [7.6, 0.96, 2.06],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS05_Str_top03",
            [7.6, 0.96, 3.06],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS05_Str_top04",
            [7.6, 0.96, 4.06],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS05_Str_top05",
            [7.6, 0.96, 5.07],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS05_Str_top06",
            [7.6, 0.96, 6.08],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS05_Str_top07",
            [7.6, 0.96, 7.08],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS05_Str_top08",
            [7.6, 0.96, 8.08],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS05_Str_top09",
            [7.6, 0.96, 9.08],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS06_Str_top01",
            [4.88, 0.96, 1.0],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS06_Str_top02",
            [4.88, 0.96, 2.0],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS06_Str_top03",
            [4.88, 0.96, 3.0],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS06_Str_top04",
            [4.88, 0.96, 4.0],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS06_Str_top05",
            [4.88, 0.96, 4.99],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS06_Str_top06",
            [4.88, 0.96, 5.97],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS06_Str_top07",
            [4.88, 0.96, 6.97],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS06_Str_top08",
            [4.88, 0.96, 7.97],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS06_Str_top09",
            [4.88, 0.96, 8.97],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Str_top01",
            [2.48, 0.96, 0.96],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Str_top02",
            [2.48, 0.96, 1.96],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Str_top03",
            [2.48, 0.96, 2.96],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Str_top04",
            [2.48, 0.96, 3.96],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Str_top05",
            [2.48, 0.96, 4.97],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Str_top06",
            [2.48, 0.96, 5.98],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Str_top07",
            [2.48, 0.96, 6.98],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Str_top08",
            [2.48, 0.96, 7.98],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Str_top09",
            [2.48, 0.96, 8.98],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Tmp_bot01",
            [17.58, 0.04, 1.04],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Tmp_bot02",
            [17.58, 0.04, 2.04],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Tmp_bot03",
            [17.58, 0.04, 3.04],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Tmp_bot04",
            [17.58, 0.04, 4.04],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Tmp_bot05",
            [17.58, 0.04, 5.01],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Tmp_bot06",
            [17.58, 0.04, 5.98],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Tmp_bot07",
            [17.58, 0.04, 6.98],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Tmp_bot08",
            [17.58, 0.04, 7.98],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Tmp_bot09",
            [17.58, 0.04, 8.98],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Tmp_bot01",
            [10.02, 0.04, 1.05],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Tmp_bot02",
            [10.02, 0.04, 2.05],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Tmp_bot03",
            [10.02, 0.04, 3.05],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Tmpr_bot04",
            [10.02, 0.04, 4.05],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Tmp_bot05",
            [10.02, 0.04, 5.02],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Tmp_bot06",
            [10.02, 0.04, 5.98],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Tmp_bot07",
            [10.02, 0.04, 6.98],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Tmp_bot08",
            [10.02, 0.04, 7.98],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Tmp_bot09",
            [10.02, 0.04, 8.98],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Tmp_bot01",
            [2.81, 0.04, 0.96],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Tmp_bot02",
            [2.81, 0.04, 1.96],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Tmp_bot03",
            [2.81, 0.04, 2.96],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Tmp_bot04",
            [2.81, 0.04, 3.96],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Tmp_bot05",
            [2.81, 0.04, 4.93],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Tmp_bot06",
            [2.81, 0.04, 5.9],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Tmp_bot07",
            [2.81, 0.04, 6.9],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Tmp_bot08",
            [2.81, 0.04, 7.9],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Tmp_bot09",
            [2.81, 0.04, 8.9],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Tmp_top01",
            [17.84, 0.96, 1.11],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Tmp_top02",
            [17.84, 0.96, 2.11],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Tmp_top03",
            [17.84, 0.96, 3.11],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Tmp_top04",
            [17.84, 0.96, 4.11],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Tmp_top05",
            [17.84, 0.96, 5.07],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Tmp_top06",
            [17.84, 0.96, 6.03],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Tmp_top07",
            [17.84, 0.96, 7.03],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Tmp_top08",
            [17.84, 0.96, 8.03],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS01_Tmp_top09",
            [17.84, 0.96, 9.03],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Tmp_top01",
            [10.02, 0.96, 1.08],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Tmp_top02",
            [10.02, 0.96, 2.08],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Tmp_top03",
            [10.02, 0.96, 3.08],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Tmp_top04",
            [10.02, 0.96, 4.08],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Tmp_top05",
            [10.02, 0.96, 5.07],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Tmp_top06",
            [10.02, 0.96, 6.06],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Tmp_top07",
            [10.02, 0.96, 7.06],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Tmp_top08",
            [10.02, 0.96, 8.06],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS04_Tmp_top09",
            [10.02, 0.96, 9.06],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Tmp_top01",
            [2.81, 0.96, 0.92],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Tmp_top02",
            [2.81, 0.96, 1.92],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Tmp_top03",
            [2.81, 0.96, 2.92],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Tmp_top04",
            [2.81, 0.96, 3.92],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Tmp_top05",
            [2.81, 0.96, 4.89],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Tmp_top06",
            [2.81, 0.96, 5.86],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Tmp_top07",
            [2.81, 0.96, 6.86],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Tmp_top08",
            [2.81, 0.96, 7.86],
            [0.3, 0.1, 0.6]
          )}
          {renderSensor(
            props.sensorColours,
            "SF_FBG_NS07_Tmp_top09",
            [2.81, 0.96, 8.86],
            [0.3, 0.1, 0.6]
          )}
        </group>
      </scene>
    </group>
  );
}
