/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()

  const { nodes, materials } = useLoader(GLTFLoader, "/Users/lawrence/Documents/Projects/nrfis/frontend/app/assets/duck.glb");

  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="Scene">
        <group name="Cube000" position={[0.32, 2.32, 10.73]}>
          <mesh material={materials['BASE.005']} geometry={nodes['Cube.001_0'].geometry} name="Cube.001_0" />
          <mesh material={materials.VENTANA} geometry={nodes['Cube.001_1'].geometry} name="Cube.001_1" />
          <mesh material={materials.sillones} geometry={nodes['Cube.001_2'].geometry} name="Cube.001_2" />
          <mesh material={materials.carts} geometry={nodes['Cube.001_3'].geometry} name="Cube.001_3" />
        </group>
      </scene>
    </group>
  )
}
