from sqlalchemy import Column, DateTime, Float

from . import Base

# Package C - Strong floor
class StrongFloor(Base):
    __tablename__ = "strong_floor_fbg"

    timestamp = Column(DateTime, primary_key=True)

    # SF-FBG-EW01bot-Str  N.B. measurements stored seperately to avoid ARRAY memory overhead
    A1 = Column(Float)
    A2 = Column(Float)
    A3 = Column(Float)
    A4 = Column(Float)
    A5 = Column(Float)
    A6 = Column(Float)
    A7 = Column(Float)
    A8 = Column(Float)
    A9 = Column(Float)
    A10 = Column(Float)
    A11 = Column(Float)
    A12 = Column(Float)
    A13 = Column(Float)
    A14 = Column(Float)
    A15 = Column(Float)
    A16 = Column(Float)
    A17 = Column(Float)
    A18 = Column(Float)
    A19 = Column(Float)
    A20 = Column(Float)

    # SF-FBG-EW01top-Str
    B1 = Column(Float)
    B2 = Column(Float)
    B3 = Column(Float)
    B4 = Column(Float)
    B5 = Column(Float)
    B6 = Column(Float)
    B7 = Column(Float)
    B8 = Column(Float)
    B9 = Column(Float)
    B10 = Column(Float)
    B11 = Column(Float)
    B12 = Column(Float)
    B13 = Column(Float)
    B14 = Column(Float)
    B15 = Column(Float)
    B16 = Column(Float)
    B17 = Column(Float)
    B18 = Column(Float)
    B19 = Column(Float)
    B20 = Column(Float)

    # SF-FBG-EW02bot-Str
    C1 = Column(Float)
    C2 = Column(Float)
    C3 = Column(Float)
    C4 = Column(Float)
    C5 = Column(Float)
    C6 = Column(Float)
    C7 = Column(Float)
    C8 = Column(Float)
    C9 = Column(Float)
    C10 = Column(Float)
    C11 = Column(Float)
    C12 = Column(Float)
    C13 = Column(Float)
    C14 = Column(Float)
    C15 = Column(Float)
    C16 = Column(Float)
    C17 = Column(Float)
    C18 = Column(Float)
    C19 = Column(Float)
    C20 = Column(Float)

    # SF-FBG-EW02top-Str
    D1 = Column(Float)
    D2 = Column(Float)
    D3 = Column(Float)
    D4 = Column(Float)
    D5 = Column(Float)
    D6 = Column(Float)
    D7 = Column(Float)
    D8 = Column(Float)
    D9 = Column(Float)
    D10 = Column(Float)
    D11 = Column(Float)
    D12 = Column(Float)
    D13 = Column(Float)
    D14 = Column(Float)
    D15 = Column(Float)
    D16 = Column(Float)
    D17 = Column(Float)
    D18 = Column(Float)
    D19 = Column(Float)
    D20 = Column(Float)

    # SF-FBG-EW03bot-Str
    E1 = Column(Float)
    E2 = Column(Float)
    E3 = Column(Float)
    E4 = Column(Float)
    E5 = Column(Float)
    E6 = Column(Float)
    E7 = Column(Float)
    E8 = Column(Float)
    E9 = Column(Float)
    E10 = Column(Float)
    E11 = Column(Float)
    E12 = Column(Float)
    E13 = Column(Float)
    E14 = Column(Float)
    E15 = Column(Float)
    E16 = Column(Float)
    E17 = Column(Float)
    E18 = Column(Float)
    E19 = Column(Float)
    E20 = Column(Float)

    # SF-FBG-EW03top-Str
    F1 = Column(Float)
    F2 = Column(Float)
    F3 = Column(Float)
    F4 = Column(Float)
    F5 = Column(Float)
    F6 = Column(Float)
    F7 = Column(Float)
    F8 = Column(Float)
    F9 = Column(Float)
    F10 = Column(Float)
    F11 = Column(Float)
    F12 = Column(Float)
    F13 = Column(Float)
    F14 = Column(Float)
    F15 = Column(Float)
    F16 = Column(Float)
    F17 = Column(Float)
    F18 = Column(Float)
    F19 = Column(Float)
    F20 = Column(Float)

    # SF-FBG-NS01bot/top-Str
    G1 = Column(Float)
    G2 = Column(Float)
    G3 = Column(Float)
    G4 = Column(Float)
    G5 = Column(Float)
    G6 = Column(Float)
    G7 = Column(Float)
    G8 = Column(Float)
    G9 = Column(Float)
    G12 = Column(Float)
    G13 = Column(Float)
    G14 = Column(Float)
    G15 = Column(Float)
    G16 = Column(Float)
    G17 = Column(Float)
    G18 = Column(Float)
    G19 = Column(Float)
    G20 = Column(Float)

    # SF-FBG-NS02bot/top-Str
    H1 = Column(Float)
    H2 = Column(Float)
    H3 = Column(Float)
    H4 = Column(Float)
    H5 = Column(Float)
    H6 = Column(Float)
    H7 = Column(Float)
    H8 = Column(Float)
    H9 = Column(Float)
    H12 = Column(Float)
    H13 = Column(Float)
    H14 = Column(Float)
    H15 = Column(Float)
    H16 = Column(Float)
    H17 = Column(Float)
    H18 = Column(Float)
    H19 = Column(Float)
    H20 = Column(Float)

    # SF-FBG-NS03bot/top-Str
    I1 = Column(Float)
    I2 = Column(Float)
    I3 = Column(Float)
    I4 = Column(Float)
    I5 = Column(Float)
    I6 = Column(Float)
    I7 = Column(Float)
    I8 = Column(Float)
    I9 = Column(Float)
    I12 = Column(Float)
    I13 = Column(Float)
    I14 = Column(Float)
    I15 = Column(Float)
    I16 = Column(Float)
    I17 = Column(Float)
    I18 = Column(Float)
    I19 = Column(Float)

    # SF-FBG-NS04bot/top-Str
    J1 = Column(Float)
    J2 = Column(Float)
    J3 = Column(Float)
    J4 = Column(Float)
    J5 = Column(Float)
    J6 = Column(Float)
    J7 = Column(Float)
    J8 = Column(Float)
    J9 = Column(Float)
    J12 = Column(Float)
    J13 = Column(Float)
    J14 = Column(Float)
    J15 = Column(Float)
    J16 = Column(Float)
    J17 = Column(Float)
    J18 = Column(Float)
    J19 = Column(Float)
    J20 = Column(Float)

    # SF-FBG-NS05bot/top-Str
    K1 = Column(Float)
    K2 = Column(Float)
    K3 = Column(Float)
    K4 = Column(Float)
    K5 = Column(Float)
    K6 = Column(Float)
    K7 = Column(Float)
    K8 = Column(Float)
    K9 = Column(Float)
    K12 = Column(Float)
    K13 = Column(Float)
    K14 = Column(Float)
    K15 = Column(Float)
    K16 = Column(Float)
    K17 = Column(Float)
    K18 = Column(Float)
    K19 = Column(Float)
    K20 = Column(Float)

    # SF-FBG-NS06bot/top-Str
    L1 = Column(Float)
    L2 = Column(Float)
    L3 = Column(Float)
    L4 = Column(Float)
    L5 = Column(Float)
    L6 = Column(Float)
    L7 = Column(Float)
    L8 = Column(Float)
    L9 = Column(Float)
    L12 = Column(Float)
    L13 = Column(Float)
    L14 = Column(Float)
    L15 = Column(Float)
    L16 = Column(Float)
    L17 = Column(Float)
    L18 = Column(Float)
    L19 = Column(Float)
    L20 = Column(Float)

    # SF-FBG-NS07bot/top-Str
    M1 = Column(Float)
    M2 = Column(Float)
    M3 = Column(Float)
    M4 = Column(Float)
    M5 = Column(Float)
    M6 = Column(Float)
    M7 = Column(Float)
    M8 = Column(Float)
    M9 = Column(Float)
    M12 = Column(Float)
    M13 = Column(Float)
    M14 = Column(Float)
    M15 = Column(Float)
    M16 = Column(Float)
    M17 = Column(Float)
    M18 = Column(Float)
    M19 = Column(Float)
    M20 = Column(Float)

    # SF-FBG-NS01bot/top-Tmp
    N1 = Column(Float)
    N2 = Column(Float)
    N3 = Column(Float)
    N4 = Column(Float)
    N5 = Column(Float)
    N6 = Column(Float)
    N7 = Column(Float)
    N8 = Column(Float)
    N9 = Column(Float)
    N12 = Column(Float)
    N13 = Column(Float)
    N14 = Column(Float)
    N15 = Column(Float)
    N16 = Column(Float)
    N17 = Column(Float)
    N18 = Column(Float)
    N19 = Column(Float)
    N20 = Column(Float)

    # SF-FBG-NS04bot/top-Tmp
    O1 = Column(Float)
    O2 = Column(Float)
    O3 = Column(Float)
    O4 = Column(Float)
    O5 = Column(Float)
    O6 = Column(Float)
    O7 = Column(Float)
    O8 = Column(Float)
    O9 = Column(Float)
    O12 = Column(Float)
    O13 = Column(Float)
    O14 = Column(Float)
    O15 = Column(Float)
    O16 = Column(Float)
    O17 = Column(Float)
    O18 = Column(Float)
    O19 = Column(Float)
    O20 = Column(Float)

    # SF-FBG-NS07bot/top-Tmp
    P1 = Column(Float)
    P2 = Column(Float)
    P3 = Column(Float)
    P4 = Column(Float)
    P5 = Column(Float)
    P6 = Column(Float)
    P7 = Column(Float)
    P8 = Column(Float)
    P9 = Column(Float)
    P12 = Column(Float)
    P13 = Column(Float)
    P14 = Column(Float)
    P15 = Column(Float)
    P16 = Column(Float)
    P17 = Column(Float)
    P18 = Column(Float)
    P19 = Column(Float)
    P20 = Column(Float)
